<?php

namespace Alloservice\AdminBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAll($niv, $direction = null)
	{
		$qb = $this 	->createQueryBuilder('s')
						->orderBy('s.service','ASC');
		if ($niv == 'niv-1') {
			$qb->where('s.service is null AND s.supService is null');
		}elseif($niv == 'niv-2'){
			$qb->where('s.service is not null AND s.supService is null');
		}elseif($niv == 'niv-3'){
			$qb->where('s.service is null AND s.supService is not null');
		}
		if (!is_null($direction)) {
			$qb->addOrderBy('s.id',$direction);
		}else{
			$qb->addOrderBy('s.id','DESC');
		}
		return $qb->getQuery();	
	}

	public function getCategories()
	{
		$qb = $this 	->createQueryBuilder('s')
						->where('s.service is null AND s.supService is null')
						->orderBy('s.id','ASC');
		return $qb->getQuery();	
	}


	public function getTop($limit)
	{
		$qb = $this 	->createQueryBuilder('s')
						->where('s.service is null AND s.supService is not null')
						->orderBy('s.id','ASC')
						->getQuery()
						->setFirstResult(0)
        				->setMaxResults($limit)
        				->getResult();
		return $qb;	
	}
}
