<?php

namespace Alloservice\UserBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function loadUserByEmail($email)
    {
        return $this->createQueryBuilder('u')
            ->where('u.email = :email')
            ->setParameter('email', $email)
            ->getQuery()
            ->getOneOrNullResult(); 
    }

    public function getAll($role)
    {
    	$qb = $this 	->createQueryBuilder('u')
    					->where('u.roles LIKE :role')
    					->setParameter('role','%'.$role.'%')
    					->orderBy('u.id','DESC')
    					->getQuery();
    	return $qb;
    }
}
