<?php

namespace Alloservice\BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAll($direction = null)
	{
		$qb = $this 	->createQueryBuilder('a');
		if (!is_null($direction)) {
			$qb->orderBy('a.id',$direction);
		}else{
			$qb->orderBy('a.id','DESC');
		}
		return $qb->getQuery();
	}

	public function getLastArticle()
	{
		$qb = $this 	->createQueryBuilder('c')
						->where('c.state = true')
						->orderBy('c.id','DESC')
						->getQuery()
						->setFirstResult(0)
        				->setMaxResults(1)
        				->getResult();
        if (empty($qb)) {
        	return null;
        }
		return $qb[0];
	}

	public function getArticles($notId = null)
	{
		$qb = $this 	->createQueryBuilder('a')
						->where('a.state = true')
						->orderBy('a.id','DESC');
		if (!is_null($notId)) {
			$qb 	->andWhere('a.id != :id')
					->setParameter('id',$notId);
		}
		$qb->getQuery();
		return $qb;
	}

	public function getArticlesByCategory($category)
	{
		$qb = $this 	->createQueryBuilder('a')
						->where('a.state = true')
						->andWhere('a.category = :category')
						->setParameter('category',$category)
						->orderBy('a.id','DESC')
						->getQuery();
		return $qb;
	}

	public function getLastArticles($notId = null, $limit = null)
	{
		$qb = $this 	->createQueryBuilder('a')
						->where('a.state = true')
						->orderBy('a.id','DESC');
		if (!is_null($notId)) {
			$qb 	->andWhere('a.id != :id')
					->setParameter('id',$notId);
		}
		if (!is_null($limit)) {
			$qb 	->setFirstResult(0)
        			->setMaxResults($limit);
		}
		return $qb->getQuery()->getResult();
	}
}
